bull = path ;
path = dynamic path | static path ;
dynamic path = ( '((' , steps , '))' ) | ( '(' , steps , ')' ) ;
static path = ( '[[' , steps , ']]' ) | ( '[' , steps , ']' ) ;
steps = angel , [ step left , [ link ] ] , [ step right , [ steps ] ] ;
link = asymmetric link | symmetric link | knot ;
asymmetric link = { angel , point right } , [ heavy knot ] , { point left , angel } ;
symmetric link = point left , angel , point right ;
point right = light point right | heavy point right ;
point left = light point left | heavy point left ;
light point right = '>' ;
heavy point right = '>>' ;
light point left = '<' ;
heavy point left = '<<' ;
step left = light step left | heavy step left ;
step right = light step right | heavy step right ;
light step left = '\' ;
heavy step left = '\\' ;
light step right = '/' ;
heavy step right = '//' ;
light step up = '|' ;
heavy step up = '||' ;
heavy knot = '&&' ;
knot = '&' ;
angel = name | unknown | superpath | definition | caller | argument | filter | count | length ;
unknown = '?' ;
superpath = '^' ;
definition = '!' ;
caller = '^@' ;
argument = '@' ;
filter = '*' ;
count = '#' ;
length = '#' , digit , { digit } , [ '.' , digit , { digit } ] ;
WS = white space ;
white space = ' ' | '\t' | '\n' ;
letter = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R"
       | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j"
       | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"  ;
digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
